### ISSUE TITLE
wrong mesh link when generate reference results

### ISSUE THREAD

**Issue by beliaev-maksim** [ansys/aedt-testing#197]
both point to the same folder, while reference results are stored in `reference_folder`
![image](https://user-images.githubusercontent.com/51964909/179387708-55c1fed9-9fc2-40ff-b910-a76297fa8a88.png)
![image](https://user-images.githubusercontent.com/51964909/179387714-1b65a5ba-db12-46ef-a569-8c7b9124b080.png)

**Comment by Samuelopez-ansys** [comment]
@beliaev-maksim 

I have tested this issue with the project "5G_SIW_Aperture_Antenna_06142022", with 2 HFSS designs, and once the regression test finished, the number of files inside reference_folder/AEDT_PROJECT_NAME/prof is 8 (4 from the reference project and the new 4 created in the regression test).
![image](https://user-images.githubusercontent.com/85613111/179461664-bc0a62c0-61d0-4092-b238-8a20f927382f.png)


What is the issue? If I am not wrong it works as expected, because the user could copy the results folder to any location and it should work.

**Comment by beliaev-maksim** [comment]
but for me on Linux I get file not found, basically it does not exist

**Comment by Samuelopez-ansys** [comment]
Then it could be an issue when we export the profile files from the initial reference folder to the new one because in Windows is working as expected. 

Is it happening to all the projects or only to this one?

In the new reference folder are not copied the reference profiles?

**Comment by beliaev-maksim** [comment]
@Samuelopez-ansys 
did you check it on Linux?
