### ISSUE TITLE
Project report for [Project] does not exist

### ISSUE THREAD

**Issue by pradeep-maharana** [ansys/aedt-testing#213]
Correlation plot is generated when comparing 2022R1 and 2022R2 result. However, the correlation plot is not generated when comparing 2022R1/R2 with 2023R1. Getting "error_exception" with the error message "Project report for [myProject] does not exist".

**Comment by Samuelopez-ansys** [comment]
@pradeep-maharana 

Thanks for raising the issue, we have detected it yesterday. The issue is in the new 23R1 build, it creates automatically a new project with the suffix 'parasolid' for example for a project called 'antenna', if you open the project, automatically the project will be saved as 'antenna_parasolid', and it was not expected. 

We are close to finding a solution.
